### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by vgoklani** [polyaxon/polyaxon-quick-start#1]
How does this compare to Hyperopt?

**Comment by mouradmourafiq** [comment]
@vgoklani Polyaxon is a platform for reproducible machine learning on Kubernetes, and hyperparameter tuning is only one of the features the platform provides.

On the other hand, Hyperopt is a Python library for hyperparameter optimization.

Hyperopt supports more algorithms compared to Polyaxon when it comes to hyperparameter optimization, that being said, Polyaxon provides other interfaces that simplify training and reproducing deep learning and machine learning algorithms on Kubernetes.
